version: '3.8'
services:
  postgresql-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - '6379:6379'

volumes:
  postgres-data:
