import { Cities } from 'src/raja-ongkir/entity/citites.entity';
import { DataSource } from 'typeorm';

export class CitiesSeeder {
  public async run(dataSource: DataSource): Promise<void> {
    const citiesRepository = dataSource.getRepository(Cities);

    const existingCities = await citiesRepository.find();
    if (existingCities.length > 0) return;

    const cities = [
      {
        id: Number('1'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Barat',
        postal_code: '23681',
      },
      {
        id: Number('2'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Barat Daya',
        postal_code: '23764',
      },
      {
        id: Number('3'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Besar',
        postal_code: '23951',
      },
      {
        id: Number('4'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Jaya',
        postal_code: '23654',
      },
      {
        id: Number('5'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Selatan',
        postal_code: '23719',
      },
      {
        id: Number('6'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Singkil',
        postal_code: '24785',
      },
      {
        id: Number('7'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Tamiang',
        postal_code: '24476',
      },
      {
        id: Number('8'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Tengah',
        postal_code: '24511',
      },
      {
        id: Number('9'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Tenggara',
        postal_code: '24611',
      },
      {
        id: Number('10'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Timur',
        postal_code: '24454',
      },
      {
        id: Number('11'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Aceh Utara',
        postal_code: '24382',
      },
      {
        id: Number('12'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Agam',
        postal_code: '26411',
      },
      {
        id: Number('13'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Alor',
        postal_code: '85811',
      },
      {
        id: Number('14'),
        province_id: Number('19'),
        type: 'Kota',
        name: 'Ambon',
        postal_code: '97222',
      },
      {
        id: Number('15'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Asahan',
        postal_code: '21214',
      },
      {
        id: Number('16'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Asmat',
        postal_code: '99777',
      },
      {
        id: Number('17'),
        province_id: Number('1'),
        type: 'Kabupaten',
        name: 'Badung',
        postal_code: '80351',
      },
      {
        id: Number('18'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Balangan',
        postal_code: '71611',
      },
      {
        id: Number('19'),
        province_id: Number('15'),
        type: 'Kota',
        name: 'Balikpapan',
        postal_code: '76111',
      },
      {
        id: Number('20'),
        province_id: Number('21'),
        type: 'Kota',
        name: 'Banda Aceh',
        postal_code: '23238',
      },
      {
        id: Number('21'),
        province_id: Number('18'),
        type: 'Kota',
        name: 'Bandar Lampung',
        postal_code: '35139',
      },
      {
        id: Number('22'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Bandung',
        postal_code: '40311',
      },
      {
        id: Number('23'),
        province_id: Number('9'),
        type: 'Kota',
        name: 'Bandung',
        postal_code: '40111',
      },
      {
        id: Number('24'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Bandung Barat',
        postal_code: '40721',
      },
      {
        id: Number('25'),
        province_id: Number('29'),
        type: 'Kabupaten',
        name: 'Banggai',
        postal_code: '94711',
      },
      {
        id: Number('26'),
        province_id: Number('29'),
        type: 'Kabupaten',
        name: 'Banggai Kepulauan',
        postal_code: '94881',
      },
      {
        id: Number('27'),
        province_id: Number('2'),
        type: 'Kabupaten',
        name: 'Bangka',
        postal_code: '33212',
      },
      {
        id: Number('28'),
        province_id: Number('2'),
        type: 'Kabupaten',
        name: 'Bangka Barat',
        postal_code: '33315',
      },
      {
        id: Number('29'),
        province_id: Number('2'),
        type: 'Kabupaten',
        name: 'Bangka Selatan',
        postal_code: '33719',
      },
      {
        id: Number('30'),
        province_id: Number('2'),
        type: 'Kabupaten',
        name: 'Bangka Tengah',
        postal_code: '33613',
      },
      {
        id: Number('31'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Bangkalan',
        postal_code: '69118',
      },
      {
        id: Number('32'),
        province_id: Number('1'),
        type: 'Kabupaten',
        name: 'Bangli',
        postal_code: '80619',
      },
      {
        id: Number('33'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Banjar',
        postal_code: '70619',
      },
      {
        id: Number('34'),
        province_id: Number('9'),
        type: 'Kota',
        name: 'Banjar',
        postal_code: '46311',
      },
      {
        id: Number('35'),
        province_id: Number('13'),
        type: 'Kota',
        name: 'Banjarbaru',
        postal_code: '70712',
      },
      {
        id: Number('36'),
        province_id: Number('13'),
        type: 'Kota',
        name: 'Banjarmasin',
        postal_code: '70117',
      },
      {
        id: Number('37'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Banjarnegara',
        postal_code: '53419',
      },
      {
        id: Number('38'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Bantaeng',
        postal_code: '92411',
      },
      {
        id: Number('39'),
        province_id: Number('5'),
        type: 'Kabupaten',
        name: 'Bantul',
        postal_code: '55715',
      },
      {
        id: Number('40'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Banyuasin',
        postal_code: '30911',
      },
      {
        id: Number('41'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Banyumas',
        postal_code: '53114',
      },
      {
        id: Number('42'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Banyuwangi',
        postal_code: '68416',
      },
      {
        id: Number('43'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Barito Kuala',
        postal_code: '70511',
      },
      {
        id: Number('44'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Barito Selatan',
        postal_code: '73711',
      },
      {
        id: Number('45'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Barito Timur',
        postal_code: '73671',
      },
      {
        id: Number('46'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Barito Utara',
        postal_code: '73881',
      },
      {
        id: Number('47'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Barru',
        postal_code: '90719',
      },
      {
        id: Number('48'),
        province_id: Number('17'),
        type: 'Kota',
        name: 'Batam',
        postal_code: '29413',
      },
      {
        id: Number('49'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Batang',
        postal_code: '51211',
      },
      {
        id: Number('50'),
        province_id: Number('8'),
        type: 'Kabupaten',
        name: 'Batang Hari',
        postal_code: '36613',
      },
      {
        id: Number('51'),
        province_id: Number('11'),
        type: 'Kota',
        name: 'Batu',
        postal_code: '65311',
      },
      {
        id: Number('52'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Batu Bara',
        postal_code: '21655',
      },
      {
        id: Number('53'),
        province_id: Number('30'),
        type: 'Kota',
        name: 'Bau-Bau',
        postal_code: '93719',
      },
      {
        id: Number('54'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Bekasi',
        postal_code: '17837',
      },
      {
        id: Number('55'),
        province_id: Number('9'),
        type: 'Kota',
        name: 'Bekasi',
        postal_code: '17121',
      },
      {
        id: Number('56'),
        province_id: Number('2'),
        type: 'Kabupaten',
        name: 'Belitung',
        postal_code: '33419',
      },
      {
        id: Number('57'),
        province_id: Number('2'),
        type: 'Kabupaten',
        name: 'Belitung Timur',
        postal_code: '33519',
      },
      {
        id: Number('58'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Belu',
        postal_code: '85711',
      },
      {
        id: Number('59'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Bener Meriah',
        postal_code: '24581',
      },
      {
        id: Number('60'),
        province_id: Number('26'),
        type: 'Kabupaten',
        name: 'Bengkalis',
        postal_code: '28719',
      },
      {
        id: Number('61'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Bengkayang',
        postal_code: '79213',
      },
      {
        id: Number('62'),
        province_id: Number('4'),
        type: 'Kota',
        name: 'Bengkulu',
        postal_code: '38229',
      },
      {
        id: Number('63'),
        province_id: Number('4'),
        type: 'Kabupaten',
        name: 'Bengkulu Selatan',
        postal_code: '38519',
      },
      {
        id: Number('64'),
        province_id: Number('4'),
        type: 'Kabupaten',
        name: 'Bengkulu Tengah',
        postal_code: '38319',
      },
      {
        id: Number('65'),
        province_id: Number('4'),
        type: 'Kabupaten',
        name: 'Bengkulu Utara',
        postal_code: '38619',
      },
      {
        id: Number('66'),
        province_id: Number('15'),
        type: 'Kabupaten',
        name: 'Berau',
        postal_code: '77311',
      },
      {
        id: Number('67'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Biak Numfor',
        postal_code: '98119',
      },
      {
        id: Number('68'),
        province_id: Number('22'),
        type: 'Kabupaten',
        name: 'Bima',
        postal_code: '84171',
      },
      {
        id: Number('69'),
        province_id: Number('22'),
        type: 'Kota',
        name: 'Bima',
        postal_code: '84139',
      },
      {
        id: Number('70'),
        province_id: Number('34'),
        type: 'Kota',
        name: 'Binjai',
        postal_code: '20712',
      },
      {
        id: Number('71'),
        province_id: Number('17'),
        type: 'Kabupaten',
        name: 'Bintan',
        postal_code: '29135',
      },
      {
        id: Number('72'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Bireuen',
        postal_code: '24219',
      },
      {
        id: Number('73'),
        province_id: Number('31'),
        type: 'Kota',
        name: 'Bitung',
        postal_code: '95512',
      },
      {
        id: Number('74'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Blitar',
        postal_code: '66171',
      },
      {
        id: Number('75'),
        province_id: Number('11'),
        type: 'Kota',
        name: 'Blitar',
        postal_code: '66124',
      },
      {
        id: Number('76'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Blora',
        postal_code: '58219',
      },
      {
        id: Number('77'),
        province_id: Number('7'),
        type: 'Kabupaten',
        name: 'Boalemo',
        postal_code: '96319',
      },
      {
        id: Number('78'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Bogor',
        postal_code: '16911',
      },
      {
        id: Number('79'),
        province_id: Number('9'),
        type: 'Kota',
        name: 'Bogor',
        postal_code: '16119',
      },
      {
        id: Number('80'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Bojonegoro',
        postal_code: '62119',
      },
      {
        id: Number('81'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Bolaang Mongondow (Bolmong)',
        postal_code: '95755',
      },
      {
        id: Number('82'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Bolaang Mongondow Selatan',
        postal_code: '95774',
      },
      {
        id: Number('83'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Bolaang Mongondow Timur',
        postal_code: '95783',
      },
      {
        id: Number('84'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Bolaang Mongondow Utara',
        postal_code: '95765',
      },
      {
        id: Number('85'),
        province_id: Number('30'),
        type: 'Kabupaten',
        name: 'Bombana',
        postal_code: '93771',
      },
      {
        id: Number('86'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Bondowoso',
        postal_code: '68219',
      },
      {
        id: Number('87'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Bone',
        postal_code: '92713',
      },
      {
        id: Number('88'),
        province_id: Number('7'),
        type: 'Kabupaten',
        name: 'Bone Bolango',
        postal_code: '96511',
      },
      {
        id: Number('89'),
        province_id: Number('15'),
        type: 'Kota',
        name: 'Bontang',
        postal_code: '75313',
      },
      {
        id: Number('90'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Boven Digoel',
        postal_code: '99662',
      },
      {
        id: Number('91'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Boyolali',
        postal_code: '57312',
      },
      {
        id: Number('92'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Brebes',
        postal_code: '52212',
      },
      {
        id: Number('93'),
        province_id: Number('32'),
        type: 'Kota',
        name: 'Bukittinggi',
        postal_code: '26115',
      },
      {
        id: Number('94'),
        province_id: Number('1'),
        type: 'Kabupaten',
        name: 'Buleleng',
        postal_code: '81111',
      },
      {
        id: Number('95'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Bulukumba',
        postal_code: '92511',
      },
      {
        id: Number('96'),
        province_id: Number('16'),
        type: 'Kabupaten',
        name: 'Bulungan (Bulongan)',
        postal_code: '77211',
      },
      {
        id: Number('97'),
        province_id: Number('8'),
        type: 'Kabupaten',
        name: 'Bungo',
        postal_code: '37216',
      },
      {
        id: Number('98'),
        province_id: Number('29'),
        type: 'Kabupaten',
        name: 'Buol',
        postal_code: '94564',
      },
      {
        id: Number('99'),
        province_id: Number('19'),
        type: 'Kabupaten',
        name: 'Buru',
        postal_code: '97371',
      },
      {
        id: Number('100'),
        province_id: Number('19'),
        type: 'Kabupaten',
        name: 'Buru Selatan',
        postal_code: '97351',
      },
      {
        id: Number('101'),
        province_id: Number('30'),
        type: 'Kabupaten',
        name: 'Buton',
        postal_code: '93754',
      },
      {
        id: Number('102'),
        province_id: Number('30'),
        type: 'Kabupaten',
        name: 'Buton Utara',
        postal_code: '93745',
      },
      {
        id: Number('103'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Ciamis',
        postal_code: '46211',
      },
      {
        id: Number('104'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Cianjur',
        postal_code: '43217',
      },
      {
        id: Number('105'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Cilacap',
        postal_code: '53211',
      },
      {
        id: Number('106'),
        province_id: Number('3'),
        type: 'Kota',
        name: 'Cilegon',
        postal_code: '42417',
      },
      {
        id: Number('107'),
        province_id: Number('9'),
        type: 'Kota',
        name: 'Cimahi',
        postal_code: '40512',
      },
      {
        id: Number('108'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Cirebon',
        postal_code: '45611',
      },
      {
        id: Number('109'),
        province_id: Number('9'),
        type: 'Kota',
        name: 'Cirebon',
        postal_code: '45116',
      },
      {
        id: Number('110'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Dairi',
        postal_code: '22211',
      },
      {
        id: Number('111'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Deiyai (Deliyai)',
        postal_code: '98784',
      },
      {
        id: Number('112'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Deli Serdang',
        postal_code: '20511',
      },
      {
        id: Number('113'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Demak',
        postal_code: '59519',
      },
      {
        id: Number('114'),
        province_id: Number('1'),
        type: 'Kota',
        name: 'Denpasar',
        postal_code: '80227',
      },
      {
        id: Number('115'),
        province_id: Number('9'),
        type: 'Kota',
        name: 'Depok',
        postal_code: '16416',
      },
      {
        id: Number('116'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Dharmasraya',
        postal_code: '27612',
      },
      {
        id: Number('117'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Dogiyai',
        postal_code: '98866',
      },
      {
        id: Number('118'),
        province_id: Number('22'),
        type: 'Kabupaten',
        name: 'Dompu',
        postal_code: '84217',
      },
      {
        id: Number('119'),
        province_id: Number('29'),
        type: 'Kabupaten',
        name: 'Donggala',
        postal_code: '94341',
      },
      {
        id: Number('120'),
        province_id: Number('26'),
        type: 'Kota',
        name: 'Dumai',
        postal_code: '28811',
      },
      {
        id: Number('121'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Empat Lawang',
        postal_code: '31811',
      },
      {
        id: Number('122'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Ende',
        postal_code: '86351',
      },
      {
        id: Number('123'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Enrekang',
        postal_code: '91719',
      },
      {
        id: Number('124'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Fakfak',
        postal_code: '98651',
      },
      {
        id: Number('125'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Flores Timur',
        postal_code: '86213',
      },
      {
        id: Number('126'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Garut',
        postal_code: '44126',
      },
      {
        id: Number('127'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Gayo Lues',
        postal_code: '24653',
      },
      {
        id: Number('128'),
        province_id: Number('1'),
        type: 'Kabupaten',
        name: 'Gianyar',
        postal_code: '80519',
      },
      {
        id: Number('129'),
        province_id: Number('7'),
        type: 'Kabupaten',
        name: 'Gorontalo',
        postal_code: '96218',
      },
      {
        id: Number('130'),
        province_id: Number('7'),
        type: 'Kota',
        name: 'Gorontalo',
        postal_code: '96115',
      },
      {
        id: Number('131'),
        province_id: Number('7'),
        type: 'Kabupaten',
        name: 'Gorontalo Utara',
        postal_code: '96611',
      },
      {
        id: Number('132'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Gowa',
        postal_code: '92111',
      },
      {
        id: Number('133'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Gresik',
        postal_code: '61115',
      },
      {
        id: Number('134'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Grobogan',
        postal_code: '58111',
      },
      {
        id: Number('135'),
        province_id: Number('5'),
        type: 'Kabupaten',
        name: 'Gunung Kidul',
        postal_code: '55812',
      },
      {
        id: Number('136'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Gunung Mas',
        postal_code: '74511',
      },
      {
        id: Number('137'),
        province_id: Number('34'),
        type: 'Kota',
        name: 'Gunungsitoli',
        postal_code: '22813',
      },
      {
        id: Number('138'),
        province_id: Number('20'),
        type: 'Kabupaten',
        name: 'Halmahera Barat',
        postal_code: '97757',
      },
      {
        id: Number('139'),
        province_id: Number('20'),
        type: 'Kabupaten',
        name: 'Halmahera Selatan',
        postal_code: '97911',
      },
      {
        id: Number('140'),
        province_id: Number('20'),
        type: 'Kabupaten',
        name: 'Halmahera Tengah',
        postal_code: '97853',
      },
      {
        id: Number('141'),
        province_id: Number('20'),
        type: 'Kabupaten',
        name: 'Halmahera Timur',
        postal_code: '97862',
      },
      {
        id: Number('142'),
        province_id: Number('20'),
        type: 'Kabupaten',
        name: 'Halmahera Utara',
        postal_code: '97762',
      },
      {
        id: Number('143'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Hulu Sungai Selatan',
        postal_code: '71212',
      },
      {
        id: Number('144'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Hulu Sungai Tengah',
        postal_code: '71313',
      },
      {
        id: Number('145'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Hulu Sungai Utara',
        postal_code: '71419',
      },
      {
        id: Number('146'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Humbang Hasundutan',
        postal_code: '22457',
      },
      {
        id: Number('147'),
        province_id: Number('26'),
        type: 'Kabupaten',
        name: 'Indragiri Hilir',
        postal_code: '29212',
      },
      {
        id: Number('148'),
        province_id: Number('26'),
        type: 'Kabupaten',
        name: 'Indragiri Hulu',
        postal_code: '29319',
      },
      {
        id: Number('149'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Indramayu',
        postal_code: '45214',
      },
      {
        id: Number('150'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Intan Jaya',
        postal_code: '98771',
      },
      {
        id: Number('151'),
        province_id: Number('6'),
        type: 'Kota',
        name: 'Jakarta Barat',
        postal_code: '11220',
      },
      {
        id: Number('152'),
        province_id: Number('6'),
        type: 'Kota',
        name: 'Jakarta Pusat',
        postal_code: '10540',
      },
      {
        id: Number('153'),
        province_id: Number('6'),
        type: 'Kota',
        name: 'Jakarta Selatan',
        postal_code: '12230',
      },
      {
        id: Number('154'),
        province_id: Number('6'),
        type: 'Kota',
        name: 'Jakarta Timur',
        postal_code: '13330',
      },
      {
        id: Number('155'),
        province_id: Number('6'),
        type: 'Kota',
        name: 'Jakarta Utara',
        postal_code: '14140',
      },
      {
        id: Number('156'),
        province_id: Number('8'),
        type: 'Kota',
        name: 'Jambi',
        postal_code: '36111',
      },
      {
        id: Number('157'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Jayapura',
        postal_code: '99352',
      },
      {
        id: Number('158'),
        province_id: Number('24'),
        type: 'Kota',
        name: 'Jayapura',
        postal_code: '99114',
      },
      {
        id: Number('159'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Jayawijaya',
        postal_code: '99511',
      },
      {
        id: Number('160'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Jember',
        postal_code: '68113',
      },
      {
        id: Number('161'),
        province_id: Number('1'),
        type: 'Kabupaten',
        name: 'Jembrana',
        postal_code: '82251',
      },
      {
        id: Number('162'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Jeneponto',
        postal_code: '92319',
      },
      {
        id: Number('163'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Jepara',
        postal_code: '59419',
      },
      {
        id: Number('164'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Jombang',
        postal_code: '61415',
      },
      {
        id: Number('165'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Kaimana',
        postal_code: '98671',
      },
      {
        id: Number('166'),
        province_id: Number('26'),
        type: 'Kabupaten',
        name: 'Kampar',
        postal_code: '28411',
      },
      {
        id: Number('167'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Kapuas',
        postal_code: '73583',
      },
      {
        id: Number('168'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Kapuas Hulu',
        postal_code: '78719',
      },
      {
        id: Number('169'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Karanganyar',
        postal_code: '57718',
      },
      {
        id: Number('170'),
        province_id: Number('1'),
        type: 'Kabupaten',
        name: 'Karangasem',
        postal_code: '80819',
      },
      {
        id: Number('171'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Karawang',
        postal_code: '41311',
      },
      {
        id: Number('172'),
        province_id: Number('17'),
        type: 'Kabupaten',
        name: 'Karimun',
        postal_code: '29611',
      },
      {
        id: Number('173'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Karo',
        postal_code: '22119',
      },
      {
        id: Number('174'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Katingan',
        postal_code: '74411',
      },
      {
        id: Number('175'),
        province_id: Number('4'),
        type: 'Kabupaten',
        name: 'Kaur',
        postal_code: '38911',
      },
      {
        id: Number('176'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Kayong Utara',
        postal_code: '78852',
      },
      {
        id: Number('177'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Kebumen',
        postal_code: '54319',
      },
      {
        id: Number('178'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Kediri',
        postal_code: '64184',
      },
      {
        id: Number('179'),
        province_id: Number('11'),
        type: 'Kota',
        name: 'Kediri',
        postal_code: '64125',
      },
      {
        id: Number('180'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Keerom',
        postal_code: '99461',
      },
      {
        id: Number('181'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Kendal',
        postal_code: '51314',
      },
      {
        id: Number('182'),
        province_id: Number('30'),
        type: 'Kota',
        name: 'Kendari',
        postal_code: '93126',
      },
      {
        id: Number('183'),
        province_id: Number('4'),
        type: 'Kabupaten',
        name: 'Kepahiang',
        postal_code: '39319',
      },
      {
        id: Number('184'),
        province_id: Number('17'),
        type: 'Kabupaten',
        name: 'Kepulauan Anambas',
        postal_code: '29991',
      },
      {
        id: Number('185'),
        province_id: Number('19'),
        type: 'Kabupaten',
        name: 'Kepulauan Aru',
        postal_code: '97681',
      },
      {
        id: Number('186'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Kepulauan Mentawai',
        postal_code: '25771',
      },
      {
        id: Number('187'),
        province_id: Number('26'),
        type: 'Kabupaten',
        name: 'Kepulauan Meranti',
        postal_code: '28791',
      },
      {
        id: Number('188'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Kepulauan Sangihe',
        postal_code: '95819',
      },
      {
        id: Number('189'),
        province_id: Number('6'),
        type: 'Kabupaten',
        name: 'Kepulauan Seribu',
        postal_code: '14550',
      },
      {
        id: Number('190'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Kepulauan Siau Tagulandang Biaro (Sitaro)',
        postal_code: '95862',
      },
      {
        id: Number('191'),
        province_id: Number('20'),
        type: 'Kabupaten',
        name: 'Kepulauan Sula',
        postal_code: '97995',
      },
      {
        id: Number('192'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Kepulauan Talaud',
        postal_code: '95885',
      },
      {
        id: Number('193'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Kepulauan Yapen (Yapen Waropen)',
        postal_code: '98211',
      },
      {
        id: Number('194'),
        province_id: Number('8'),
        type: 'Kabupaten',
        name: 'Kerinci',
        postal_code: '37167',
      },
      {
        id: Number('195'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Ketapang',
        postal_code: '78874',
      },
      {
        id: Number('196'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Klaten',
        postal_code: '57411',
      },
      {
        id: Number('197'),
        province_id: Number('1'),
        type: 'Kabupaten',
        name: 'Klungkung',
        postal_code: '80719',
      },
      {
        id: Number('198'),
        province_id: Number('30'),
        type: 'Kabupaten',
        name: 'Kolaka',
        postal_code: '93511',
      },
      {
        id: Number('199'),
        province_id: Number('30'),
        type: 'Kabupaten',
        name: 'Kolaka Utara',
        postal_code: '93911',
      },
      {
        id: Number('200'),
        province_id: Number('30'),
        type: 'Kabupaten',
        name: 'Konawe',
        postal_code: '93411',
      },
      {
        id: Number('201'),
        province_id: Number('30'),
        type: 'Kabupaten',
        name: 'Konawe Selatan',
        postal_code: '93811',
      },
      {
        id: Number('202'),
        province_id: Number('30'),
        type: 'Kabupaten',
        name: 'Konawe Utara',
        postal_code: '93311',
      },
      {
        id: Number('203'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Kotabaru',
        postal_code: '72119',
      },
      {
        id: Number('204'),
        province_id: Number('31'),
        type: 'Kota',
        name: 'Kotamobagu',
        postal_code: '95711',
      },
      {
        id: Number('205'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Kotawaringin Barat',
        postal_code: '74119',
      },
      {
        id: Number('206'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Kotawaringin Timur',
        postal_code: '74364',
      },
      {
        id: Number('207'),
        province_id: Number('26'),
        type: 'Kabupaten',
        name: 'Kuantan Singingi',
        postal_code: '29519',
      },
      {
        id: Number('208'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Kubu Raya',
        postal_code: '78311',
      },
      {
        id: Number('209'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Kudus',
        postal_code: '59311',
      },
      {
        id: Number('210'),
        province_id: Number('5'),
        type: 'Kabupaten',
        name: 'Kulon Progo',
        postal_code: '55611',
      },
      {
        id: Number('211'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Kuningan',
        postal_code: '45511',
      },
      {
        id: Number('212'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Kupang',
        postal_code: '85362',
      },
      {
        id: Number('213'),
        province_id: Number('23'),
        type: 'Kota',
        name: 'Kupang',
        postal_code: '85119',
      },
      {
        id: Number('214'),
        province_id: Number('15'),
        type: 'Kabupaten',
        name: 'Kutai Barat',
        postal_code: '75711',
      },
      {
        id: Number('215'),
        province_id: Number('15'),
        type: 'Kabupaten',
        name: 'Kutai Kartanegara',
        postal_code: '75511',
      },
      {
        id: Number('216'),
        province_id: Number('15'),
        type: 'Kabupaten',
        name: 'Kutai Timur',
        postal_code: '75611',
      },
      {
        id: Number('217'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Labuhan Batu',
        postal_code: '21412',
      },
      {
        id: Number('218'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Labuhan Batu Selatan',
        postal_code: '21511',
      },
      {
        id: Number('219'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Labuhan Batu Utara',
        postal_code: '21711',
      },
      {
        id: Number('220'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Lahat',
        postal_code: '31419',
      },
      {
        id: Number('221'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Lamandau',
        postal_code: '74611',
      },
      {
        id: Number('222'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Lamongan',
        postal_code: '64125',
      },
      {
        id: Number('223'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Lampung Barat',
        postal_code: '34814',
      },
      {
        id: Number('224'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Lampung Selatan',
        postal_code: '35511',
      },
      {
        id: Number('225'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Lampung Tengah',
        postal_code: '34212',
      },
      {
        id: Number('226'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Lampung Timur',
        postal_code: '34319',
      },
      {
        id: Number('227'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Lampung Utara',
        postal_code: '34516',
      },
      {
        id: Number('228'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Landak',
        postal_code: '78319',
      },
      {
        id: Number('229'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Langkat',
        postal_code: '20811',
      },
      {
        id: Number('230'),
        province_id: Number('21'),
        type: 'Kota',
        name: 'Langsa',
        postal_code: '24412',
      },
      {
        id: Number('231'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Lanny Jaya',
        postal_code: '99531',
      },
      {
        id: Number('232'),
        province_id: Number('3'),
        type: 'Kabupaten',
        name: 'Lebak',
        postal_code: '42319',
      },
      {
        id: Number('233'),
        province_id: Number('4'),
        type: 'Kabupaten',
        name: 'Lebong',
        postal_code: '39264',
      },
      {
        id: Number('234'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Lembata',
        postal_code: '86611',
      },
      {
        id: Number('235'),
        province_id: Number('21'),
        type: 'Kota',
        name: 'Lhokseumawe',
        postal_code: '24352',
      },
      {
        id: Number('236'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Lima Puluh Koto/Kota',
        postal_code: '26671',
      },
      {
        id: Number('237'),
        province_id: Number('17'),
        type: 'Kabupaten',
        name: 'Lingga',
        postal_code: '29811',
      },
      {
        id: Number('238'),
        province_id: Number('22'),
        type: 'Kabupaten',
        name: 'Lombok Barat',
        postal_code: '83311',
      },
      {
        id: Number('239'),
        province_id: Number('22'),
        type: 'Kabupaten',
        name: 'Lombok Tengah',
        postal_code: '83511',
      },
      {
        id: Number('240'),
        province_id: Number('22'),
        type: 'Kabupaten',
        name: 'Lombok Timur',
        postal_code: '83612',
      },
      {
        id: Number('241'),
        province_id: Number('22'),
        type: 'Kabupaten',
        name: 'Lombok Utara',
        postal_code: '83711',
      },
      {
        id: Number('242'),
        province_id: Number('33'),
        type: 'Kota',
        name: 'Lubuk Linggau',
        postal_code: '31614',
      },
      {
        id: Number('243'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Lumajang',
        postal_code: '67319',
      },
      {
        id: Number('244'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Luwu',
        postal_code: '91994',
      },
      {
        id: Number('245'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Luwu Timur',
        postal_code: '92981',
      },
      {
        id: Number('246'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Luwu Utara',
        postal_code: '92911',
      },
      {
        id: Number('247'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Madiun',
        postal_code: '63153',
      },
      {
        id: Number('248'),
        province_id: Number('11'),
        type: 'Kota',
        name: 'Madiun',
        postal_code: '63122',
      },
      {
        id: Number('249'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Magelang',
        postal_code: '56519',
      },
      {
        id: Number('250'),
        province_id: Number('10'),
        type: 'Kota',
        name: 'Magelang',
        postal_code: '56133',
      },
      {
        id: Number('251'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Magetan',
        postal_code: '63314',
      },
      {
        id: Number('252'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Majalengka',
        postal_code: '45412',
      },
      {
        id: Number('253'),
        province_id: Number('27'),
        type: 'Kabupaten',
        name: 'Majene',
        postal_code: '91411',
      },
      {
        id: Number('254'),
        province_id: Number('28'),
        type: 'Kota',
        name: 'Makassar',
        postal_code: '90111',
      },
      {
        id: Number('255'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Malang',
        postal_code: '65163',
      },
      {
        id: Number('256'),
        province_id: Number('11'),
        type: 'Kota',
        name: 'Malang',
        postal_code: '65112',
      },
      {
        id: Number('257'),
        province_id: Number('16'),
        type: 'Kabupaten',
        name: 'Malinau',
        postal_code: '77511',
      },
      {
        id: Number('258'),
        province_id: Number('19'),
        type: 'Kabupaten',
        name: 'Maluku Barat Daya',
        postal_code: '97451',
      },
      {
        id: Number('259'),
        province_id: Number('19'),
        type: 'Kabupaten',
        name: 'Maluku Tengah',
        postal_code: '97513',
      },
      {
        id: Number('260'),
        province_id: Number('19'),
        type: 'Kabupaten',
        name: 'Maluku Tenggara',
        postal_code: '97651',
      },
      {
        id: Number('261'),
        province_id: Number('19'),
        type: 'Kabupaten',
        name: 'Maluku Tenggara Barat',
        postal_code: '97465',
      },
      {
        id: Number('262'),
        province_id: Number('27'),
        type: 'Kabupaten',
        name: 'Mamasa',
        postal_code: '91362',
      },
      {
        id: Number('263'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Mamberamo Raya',
        postal_code: '99381',
      },
      {
        id: Number('264'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Mamberamo Tengah',
        postal_code: '99553',
      },
      {
        id: Number('265'),
        province_id: Number('27'),
        type: 'Kabupaten',
        name: 'Mamuju',
        postal_code: '91519',
      },
      {
        id: Number('266'),
        province_id: Number('27'),
        type: 'Kabupaten',
        name: 'Mamuju Utara',
        postal_code: '91571',
      },
      {
        id: Number('267'),
        province_id: Number('31'),
        type: 'Kota',
        name: 'Manado',
        postal_code: '95247',
      },
      {
        id: Number('268'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Mandailing Natal',
        postal_code: '22916',
      },
      {
        id: Number('269'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Manggarai',
        postal_code: '86551',
      },
      {
        id: Number('270'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Manggarai Barat',
        postal_code: '86711',
      },
      {
        id: Number('271'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Manggarai Timur',
        postal_code: '86811',
      },
      {
        id: Number('272'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Manokwari',
        postal_code: '98311',
      },
      {
        id: Number('273'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Manokwari Selatan',
        postal_code: '98355',
      },
      {
        id: Number('274'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Mappi',
        postal_code: '99853',
      },
      {
        id: Number('275'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Maros',
        postal_code: '90511',
      },
      {
        id: Number('276'),
        province_id: Number('22'),
        type: 'Kota',
        name: 'Mataram',
        postal_code: '83131',
      },
      {
        id: Number('277'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Maybrat',
        postal_code: '98051',
      },
      {
        id: Number('278'),
        province_id: Number('34'),
        type: 'Kota',
        name: 'Medan',
        postal_code: '20228',
      },
      {
        id: Number('279'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Melawi',
        postal_code: '78619',
      },
      {
        id: Number('280'),
        province_id: Number('8'),
        type: 'Kabupaten',
        name: 'Merangin',
        postal_code: '37319',
      },
      {
        id: Number('281'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Merauke',
        postal_code: '99613',
      },
      {
        id: Number('282'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Mesuji',
        postal_code: '34911',
      },
      {
        id: Number('283'),
        province_id: Number('18'),
        type: 'Kota',
        name: 'Metro',
        postal_code: '34111',
      },
      {
        id: Number('284'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Mimika',
        postal_code: '99962',
      },
      {
        id: Number('285'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Minahasa',
        postal_code: '95614',
      },
      {
        id: Number('286'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Minahasa Selatan',
        postal_code: '95914',
      },
      {
        id: Number('287'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Minahasa Tenggara',
        postal_code: '95995',
      },
      {
        id: Number('288'),
        province_id: Number('31'),
        type: 'Kabupaten',
        name: 'Minahasa Utara',
        postal_code: '95316',
      },
      {
        id: Number('289'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Mojokerto',
        postal_code: '61382',
      },
      {
        id: Number('290'),
        province_id: Number('11'),
        type: 'Kota',
        name: 'Mojokerto',
        postal_code: '61316',
      },
      {
        id: Number('291'),
        province_id: Number('29'),
        type: 'Kabupaten',
        name: 'Morowali',
        postal_code: '94911',
      },
      {
        id: Number('292'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Muara Enim',
        postal_code: '31315',
      },
      {
        id: Number('293'),
        province_id: Number('8'),
        type: 'Kabupaten',
        name: 'Muaro Jambi',
        postal_code: '36311',
      },
      {
        id: Number('294'),
        province_id: Number('4'),
        type: 'Kabupaten',
        name: 'Muko Muko',
        postal_code: '38715',
      },
      {
        id: Number('295'),
        province_id: Number('30'),
        type: 'Kabupaten',
        name: 'Muna',
        postal_code: '93611',
      },
      {
        id: Number('296'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Murung Raya',
        postal_code: '73911',
      },
      {
        id: Number('297'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Musi Banyuasin',
        postal_code: '30719',
      },
      {
        id: Number('298'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Musi Rawas',
        postal_code: '31661',
      },
      {
        id: Number('299'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Nabire',
        postal_code: '98816',
      },
      {
        id: Number('300'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Nagan Raya',
        postal_code: '23674',
      },
      {
        id: Number('301'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Nagekeo',
        postal_code: '86911',
      },
      {
        id: Number('302'),
        province_id: Number('17'),
        type: 'Kabupaten',
        name: 'Natuna',
        postal_code: '29711',
      },
      {
        id: Number('303'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Nduga',
        postal_code: '99541',
      },
      {
        id: Number('304'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Ngada',
        postal_code: '86413',
      },
      {
        id: Number('305'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Nganjuk',
        postal_code: '64414',
      },
      {
        id: Number('306'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Ngawi',
        postal_code: '63219',
      },
      {
        id: Number('307'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Nias',
        postal_code: '22876',
      },
      {
        id: Number('308'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Nias Barat',
        postal_code: '22895',
      },
      {
        id: Number('309'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Nias Selatan',
        postal_code: '22865',
      },
      {
        id: Number('310'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Nias Utara',
        postal_code: '22856',
      },
      {
        id: Number('311'),
        province_id: Number('16'),
        type: 'Kabupaten',
        name: 'Nunukan',
        postal_code: '77421',
      },
      {
        id: Number('312'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Ogan Ilir',
        postal_code: '30811',
      },
      {
        id: Number('313'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Ogan Komering Ilir',
        postal_code: '30618',
      },
      {
        id: Number('314'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Ogan Komering Ulu',
        postal_code: '32112',
      },
      {
        id: Number('315'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Ogan Komering Ulu Selatan',
        postal_code: '32211',
      },
      {
        id: Number('316'),
        province_id: Number('33'),
        type: 'Kabupaten',
        name: 'Ogan Komering Ulu Timur',
        postal_code: '32312',
      },
      {
        id: Number('317'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Pacitan',
        postal_code: '63512',
      },
      {
        id: Number('318'),
        province_id: Number('32'),
        type: 'Kota',
        name: 'Padang',
        postal_code: '25112',
      },
      {
        id: Number('319'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Padang Lawas',
        postal_code: '22763',
      },
      {
        id: Number('320'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Padang Lawas Utara',
        postal_code: '22753',
      },
      {
        id: Number('321'),
        province_id: Number('32'),
        type: 'Kota',
        name: 'Padang Panjang',
        postal_code: '27122',
      },
      {
        id: Number('322'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Padang Pariaman',
        postal_code: '25583',
      },
      {
        id: Number('323'),
        province_id: Number('34'),
        type: 'Kota',
        name: 'Padang Sidempuan',
        postal_code: '22727',
      },
      {
        id: Number('324'),
        province_id: Number('33'),
        type: 'Kota',
        name: 'Pagar Alam',
        postal_code: '31512',
      },
      {
        id: Number('325'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Pakpak Bharat',
        postal_code: '22272',
      },
      {
        id: Number('326'),
        province_id: Number('14'),
        type: 'Kota',
        name: 'Palangka Raya',
        postal_code: '73112',
      },
      {
        id: Number('327'),
        province_id: Number('33'),
        type: 'Kota',
        name: 'Palembang',
        postal_code: '30111',
      },
      {
        id: Number('328'),
        province_id: Number('28'),
        type: 'Kota',
        name: 'Palopo',
        postal_code: '91911',
      },
      {
        id: Number('329'),
        province_id: Number('29'),
        type: 'Kota',
        name: 'Palu',
        postal_code: '94111',
      },
      {
        id: Number('330'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Pamekasan',
        postal_code: '69319',
      },
      {
        id: Number('331'),
        province_id: Number('3'),
        type: 'Kabupaten',
        name: 'Pandeglang',
        postal_code: '42212',
      },
      {
        id: Number('332'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Pangandaran',
        postal_code: '46511',
      },
      {
        id: Number('333'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Pangkajene Kepulauan',
        postal_code: '90611',
      },
      {
        id: Number('334'),
        province_id: Number('2'),
        type: 'Kota',
        name: 'Pangkal Pinang',
        postal_code: '33115',
      },
      {
        id: Number('335'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Paniai',
        postal_code: '98765',
      },
      {
        id: Number('336'),
        province_id: Number('28'),
        type: 'Kota',
        name: 'Parepare',
        postal_code: '91123',
      },
      {
        id: Number('337'),
        province_id: Number('32'),
        type: 'Kota',
        name: 'Pariaman',
        postal_code: '25511',
      },
      {
        id: Number('338'),
        province_id: Number('29'),
        type: 'Kabupaten',
        name: 'Parigi Moutong',
        postal_code: '94411',
      },
      {
        id: Number('339'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Pasaman',
        postal_code: '26318',
      },
      {
        id: Number('340'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Pasaman Barat',
        postal_code: '26511',
      },
      {
        id: Number('341'),
        province_id: Number('15'),
        type: 'Kabupaten',
        name: 'Paser',
        postal_code: '76211',
      },
      {
        id: Number('342'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Pasuruan',
        postal_code: '67153',
      },
      {
        id: Number('343'),
        province_id: Number('11'),
        type: 'Kota',
        name: 'Pasuruan',
        postal_code: '67118',
      },
      {
        id: Number('344'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Pati',
        postal_code: '59114',
      },
      {
        id: Number('345'),
        province_id: Number('32'),
        type: 'Kota',
        name: 'Payakumbuh',
        postal_code: '26213',
      },
      {
        id: Number('346'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Pegunungan Arfak',
        postal_code: '98354',
      },
      {
        id: Number('347'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Pegunungan Bintang',
        postal_code: '99573',
      },
      {
        id: Number('348'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Pekalongan',
        postal_code: '51161',
      },
      {
        id: Number('349'),
        province_id: Number('10'),
        type: 'Kota',
        name: 'Pekalongan',
        postal_code: '51122',
      },
      {
        id: Number('350'),
        province_id: Number('26'),
        type: 'Kota',
        name: 'Pekanbaru',
        postal_code: '28112',
      },
      {
        id: Number('351'),
        province_id: Number('26'),
        type: 'Kabupaten',
        name: 'Pelalawan',
        postal_code: '28311',
      },
      {
        id: Number('352'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Pemalang',
        postal_code: '52319',
      },
      {
        id: Number('353'),
        province_id: Number('34'),
        type: 'Kota',
        name: 'Pematang Siantar',
        postal_code: '21126',
      },
      {
        id: Number('354'),
        province_id: Number('15'),
        type: 'Kabupaten',
        name: 'Penajam Paser Utara',
        postal_code: '76311',
      },
      {
        id: Number('355'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Pesawaran',
        postal_code: '35312',
      },
      {
        id: Number('356'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Pesisir Barat',
        postal_code: '35974',
      },
      {
        id: Number('357'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Pesisir Selatan',
        postal_code: '25611',
      },
      {
        id: Number('358'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Pidie',
        postal_code: '24116',
      },
      {
        id: Number('359'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Pidie Jaya',
        postal_code: '24186',
      },
      {
        id: Number('360'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Pinrang',
        postal_code: '91251',
      },
      {
        id: Number('361'),
        province_id: Number('7'),
        type: 'Kabupaten',
        name: 'Pohuwato',
        postal_code: '96419',
      },
      {
        id: Number('362'),
        province_id: Number('27'),
        type: 'Kabupaten',
        name: 'Polewali Mandar',
        postal_code: '91311',
      },
      {
        id: Number('363'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Ponorogo',
        postal_code: '63411',
      },
      {
        id: Number('364'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Pontianak',
        postal_code: '78971',
      },
      {
        id: Number('365'),
        province_id: Number('12'),
        type: 'Kota',
        name: 'Pontianak',
        postal_code: '78112',
      },
      {
        id: Number('366'),
        province_id: Number('29'),
        type: 'Kabupaten',
        name: 'Poso',
        postal_code: '94615',
      },
      {
        id: Number('367'),
        province_id: Number('33'),
        type: 'Kota',
        name: 'Prabumulih',
        postal_code: '31121',
      },
      {
        id: Number('368'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Pringsewu',
        postal_code: '35719',
      },
      {
        id: Number('369'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Probolinggo',
        postal_code: '67282',
      },
      {
        id: Number('370'),
        province_id: Number('11'),
        type: 'Kota',
        name: 'Probolinggo',
        postal_code: '67215',
      },
      {
        id: Number('371'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Pulang Pisau',
        postal_code: '74811',
      },
      {
        id: Number('372'),
        province_id: Number('20'),
        type: 'Kabupaten',
        name: 'Pulau Morotai',
        postal_code: '97771',
      },
      {
        id: Number('373'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Puncak',
        postal_code: '98981',
      },
      {
        id: Number('374'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Puncak Jaya',
        postal_code: '98979',
      },
      {
        id: Number('375'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Purbalingga',
        postal_code: '53312',
      },
      {
        id: Number('376'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Purwakarta',
        postal_code: '41119',
      },
      {
        id: Number('377'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Purworejo',
        postal_code: '54111',
      },
      {
        id: Number('378'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Raja Ampat',
        postal_code: '98489',
      },
      {
        id: Number('379'),
        province_id: Number('4'),
        type: 'Kabupaten',
        name: 'Rejang Lebong',
        postal_code: '39112',
      },
      {
        id: Number('380'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Rembang',
        postal_code: '59219',
      },
      {
        id: Number('381'),
        province_id: Number('26'),
        type: 'Kabupaten',
        name: 'Rokan Hilir',
        postal_code: '28992',
      },
      {
        id: Number('382'),
        province_id: Number('26'),
        type: 'Kabupaten',
        name: 'Rokan Hulu',
        postal_code: '28511',
      },
      {
        id: Number('383'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Rote Ndao',
        postal_code: '85982',
      },
      {
        id: Number('384'),
        province_id: Number('21'),
        type: 'Kota',
        name: 'Sabang',
        postal_code: '23512',
      },
      {
        id: Number('385'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Sabu Raijua',
        postal_code: '85391',
      },
      {
        id: Number('386'),
        province_id: Number('10'),
        type: 'Kota',
        name: 'Salatiga',
        postal_code: '50711',
      },
      {
        id: Number('387'),
        province_id: Number('15'),
        type: 'Kota',
        name: 'Samarinda',
        postal_code: '75133',
      },
      {
        id: Number('388'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Sambas',
        postal_code: '79453',
      },
      {
        id: Number('389'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Samosir',
        postal_code: '22392',
      },
      {
        id: Number('390'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Sampang',
        postal_code: '69219',
      },
      {
        id: Number('391'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Sanggau',
        postal_code: '78557',
      },
      {
        id: Number('392'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Sarmi',
        postal_code: '99373',
      },
      {
        id: Number('393'),
        province_id: Number('8'),
        type: 'Kabupaten',
        name: 'Sarolangun',
        postal_code: '37419',
      },
      {
        id: Number('394'),
        province_id: Number('32'),
        type: 'Kota',
        name: 'Sawah Lunto',
        postal_code: '27416',
      },
      {
        id: Number('395'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Sekadau',
        postal_code: '79583',
      },
      {
        id: Number('396'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Selayar (Kepulauan Selayar)',
        postal_code: '92812',
      },
      {
        id: Number('397'),
        province_id: Number('4'),
        type: 'Kabupaten',
        name: 'Seluma',
        postal_code: '38811',
      },
      {
        id: Number('398'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Semarang',
        postal_code: '50511',
      },
      {
        id: Number('399'),
        province_id: Number('10'),
        type: 'Kota',
        name: 'Semarang',
        postal_code: '50135',
      },
      {
        id: Number('400'),
        province_id: Number('19'),
        type: 'Kabupaten',
        name: 'Seram Bagian Barat',
        postal_code: '97561',
      },
      {
        id: Number('401'),
        province_id: Number('19'),
        type: 'Kabupaten',
        name: 'Seram Bagian Timur',
        postal_code: '97581',
      },
      {
        id: Number('402'),
        province_id: Number('3'),
        type: 'Kabupaten',
        name: 'Serang',
        postal_code: '42182',
      },
      {
        id: Number('403'),
        province_id: Number('3'),
        type: 'Kota',
        name: 'Serang',
        postal_code: '42111',
      },
      {
        id: Number('404'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Serdang Bedagai',
        postal_code: '20915',
      },
      {
        id: Number('405'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Seruyan',
        postal_code: '74211',
      },
      {
        id: Number('406'),
        province_id: Number('26'),
        type: 'Kabupaten',
        name: 'Siak',
        postal_code: '28623',
      },
      {
        id: Number('407'),
        province_id: Number('34'),
        type: 'Kota',
        name: 'Sibolga',
        postal_code: '22522',
      },
      {
        id: Number('408'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Sidenreng Rappang/Rapang',
        postal_code: '91613',
      },
      {
        id: Number('409'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Sidoarjo',
        postal_code: '61219',
      },
      {
        id: Number('410'),
        province_id: Number('29'),
        type: 'Kabupaten',
        name: 'Sigi',
        postal_code: '94364',
      },
      {
        id: Number('411'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Sijunjung (Sawah Lunto Sijunjung)',
        postal_code: '27511',
      },
      {
        id: Number('412'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Sikka',
        postal_code: '86121',
      },
      {
        id: Number('413'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Simalungun',
        postal_code: '21162',
      },
      {
        id: Number('414'),
        province_id: Number('21'),
        type: 'Kabupaten',
        name: 'Simeulue',
        postal_code: '23891',
      },
      {
        id: Number('415'),
        province_id: Number('12'),
        type: 'Kota',
        name: 'Singkawang',
        postal_code: '79117',
      },
      {
        id: Number('416'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Sinjai',
        postal_code: '92615',
      },
      {
        id: Number('417'),
        province_id: Number('12'),
        type: 'Kabupaten',
        name: 'Sintang',
        postal_code: '78619',
      },
      {
        id: Number('418'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Situbondo',
        postal_code: '68316',
      },
      {
        id: Number('419'),
        province_id: Number('5'),
        type: 'Kabupaten',
        name: 'Sleman',
        postal_code: '55513',
      },
      {
        id: Number('420'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Solok',
        postal_code: '27365',
      },
      {
        id: Number('421'),
        province_id: Number('32'),
        type: 'Kota',
        name: 'Solok',
        postal_code: '27315',
      },
      {
        id: Number('422'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Solok Selatan',
        postal_code: '27779',
      },
      {
        id: Number('423'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Soppeng',
        postal_code: '90812',
      },
      {
        id: Number('424'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Sorong',
        postal_code: '98431',
      },
      {
        id: Number('425'),
        province_id: Number('25'),
        type: 'Kota',
        name: 'Sorong',
        postal_code: '98411',
      },
      {
        id: Number('426'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Sorong Selatan',
        postal_code: '98454',
      },
      {
        id: Number('427'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Sragen',
        postal_code: '57211',
      },
      {
        id: Number('428'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Subang',
        postal_code: '41215',
      },
      {
        id: Number('429'),
        province_id: Number('21'),
        type: 'Kota',
        name: 'Subulussalam',
        postal_code: '24882',
      },
      {
        id: Number('430'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Sukabumi',
        postal_code: '43311',
      },
      {
        id: Number('431'),
        province_id: Number('9'),
        type: 'Kota',
        name: 'Sukabumi',
        postal_code: '43114',
      },
      {
        id: Number('432'),
        province_id: Number('14'),
        type: 'Kabupaten',
        name: 'Sukamara',
        postal_code: '74712',
      },
      {
        id: Number('433'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Sukoharjo',
        postal_code: '57514',
      },
      {
        id: Number('434'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Sumba Barat',
        postal_code: '87219',
      },
      {
        id: Number('435'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Sumba Barat Daya',
        postal_code: '87453',
      },
      {
        id: Number('436'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Sumba Tengah',
        postal_code: '87358',
      },
      {
        id: Number('437'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Sumba Timur',
        postal_code: '87112',
      },
      {
        id: Number('438'),
        province_id: Number('22'),
        type: 'Kabupaten',
        name: 'Sumbawa',
        postal_code: '84315',
      },
      {
        id: Number('439'),
        province_id: Number('22'),
        type: 'Kabupaten',
        name: 'Sumbawa Barat',
        postal_code: '84419',
      },
      {
        id: Number('440'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Sumedang',
        postal_code: '45326',
      },
      {
        id: Number('441'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Sumenep',
        postal_code: '69413',
      },
      {
        id: Number('442'),
        province_id: Number('8'),
        type: 'Kota',
        name: 'Sungaipenuh',
        postal_code: '37113',
      },
      {
        id: Number('443'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Supiori',
        postal_code: '98164',
      },
      {
        id: Number('444'),
        province_id: Number('11'),
        type: 'Kota',
        name: 'Surabaya',
        postal_code: '60119',
      },
      {
        id: Number('445'),
        province_id: Number('10'),
        type: 'Kota',
        name: 'Surakarta (Solo)',
        postal_code: '57113',
      },
      {
        id: Number('446'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Tabalong',
        postal_code: '71513',
      },
      {
        id: Number('447'),
        province_id: Number('1'),
        type: 'Kabupaten',
        name: 'Tabanan',
        postal_code: '82119',
      },
      {
        id: Number('448'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Takalar',
        postal_code: '92212',
      },
      {
        id: Number('449'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Tambrauw',
        postal_code: '98475',
      },
      {
        id: Number('450'),
        province_id: Number('16'),
        type: 'Kabupaten',
        name: 'Tana Tidung',
        postal_code: '77611',
      },
      {
        id: Number('451'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Tana Toraja',
        postal_code: '91819',
      },
      {
        id: Number('452'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Tanah Bumbu',
        postal_code: '72211',
      },
      {
        id: Number('453'),
        province_id: Number('32'),
        type: 'Kabupaten',
        name: 'Tanah Datar',
        postal_code: '27211',
      },
      {
        id: Number('454'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Tanah Laut',
        postal_code: '70811',
      },
      {
        id: Number('455'),
        province_id: Number('3'),
        type: 'Kabupaten',
        name: 'Tangerang',
        postal_code: '15914',
      },
      {
        id: Number('456'),
        province_id: Number('3'),
        type: 'Kota',
        name: 'Tangerang',
        postal_code: '15111',
      },
      {
        id: Number('457'),
        province_id: Number('3'),
        type: 'Kota',
        name: 'Tangerang Selatan',
        postal_code: '15435',
      },
      {
        id: Number('458'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Tanggamus',
        postal_code: '35619',
      },
      {
        id: Number('459'),
        province_id: Number('34'),
        type: 'Kota',
        name: 'Tanjung Balai',
        postal_code: '21321',
      },
      {
        id: Number('460'),
        province_id: Number('8'),
        type: 'Kabupaten',
        name: 'Tanjung Jabung Barat',
        postal_code: '36513',
      },
      {
        id: Number('461'),
        province_id: Number('8'),
        type: 'Kabupaten',
        name: 'Tanjung Jabung Timur',
        postal_code: '36719',
      },
      {
        id: Number('462'),
        province_id: Number('17'),
        type: 'Kota',
        name: 'Tanjung Pinang',
        postal_code: '29111',
      },
      {
        id: Number('463'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Tapanuli Selatan',
        postal_code: '22742',
      },
      {
        id: Number('464'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Tapanuli Tengah',
        postal_code: '22611',
      },
      {
        id: Number('465'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Tapanuli Utara',
        postal_code: '22414',
      },
      {
        id: Number('466'),
        province_id: Number('13'),
        type: 'Kabupaten',
        name: 'Tapin',
        postal_code: '71119',
      },
      {
        id: Number('467'),
        province_id: Number('16'),
        type: 'Kota',
        name: 'Tarakan',
        postal_code: '77114',
      },
      {
        id: Number('468'),
        province_id: Number('9'),
        type: 'Kabupaten',
        name: 'Tasikmalaya',
        postal_code: '46411',
      },
      {
        id: Number('469'),
        province_id: Number('9'),
        type: 'Kota',
        name: 'Tasikmalaya',
        postal_code: '46116',
      },
      {
        id: Number('470'),
        province_id: Number('34'),
        type: 'Kota',
        name: 'Tebing Tinggi',
        postal_code: '20632',
      },
      {
        id: Number('471'),
        province_id: Number('8'),
        type: 'Kabupaten',
        name: 'Tebo',
        postal_code: '37519',
      },
      {
        id: Number('472'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Tegal',
        postal_code: '52419',
      },
      {
        id: Number('473'),
        province_id: Number('10'),
        type: 'Kota',
        name: 'Tegal',
        postal_code: '52114',
      },
      {
        id: Number('474'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Teluk Bintuni',
        postal_code: '98551',
      },
      {
        id: Number('475'),
        province_id: Number('25'),
        type: 'Kabupaten',
        name: 'Teluk Wondama',
        postal_code: '98591',
      },
      {
        id: Number('476'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Temanggung',
        postal_code: '56212',
      },
      {
        id: Number('477'),
        province_id: Number('20'),
        type: 'Kota',
        name: 'Ternate',
        postal_code: '97714',
      },
      {
        id: Number('478'),
        province_id: Number('20'),
        type: 'Kota',
        name: 'Tidore Kepulauan',
        postal_code: '97815',
      },
      {
        id: Number('479'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Timor Tengah Selatan',
        postal_code: '85562',
      },
      {
        id: Number('480'),
        province_id: Number('23'),
        type: 'Kabupaten',
        name: 'Timor Tengah Utara',
        postal_code: '85612',
      },
      {
        id: Number('481'),
        province_id: Number('34'),
        type: 'Kabupaten',
        name: 'Toba Samosir',
        postal_code: '22316',
      },
      {
        id: Number('482'),
        province_id: Number('29'),
        type: 'Kabupaten',
        name: 'Tojo Una-Una',
        postal_code: '94683',
      },
      {
        id: Number('483'),
        province_id: Number('29'),
        type: 'Kabupaten',
        name: 'Toli-Toli',
        postal_code: '94542',
      },
      {
        id: Number('484'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Tolikara',
        postal_code: '99411',
      },
      {
        id: Number('485'),
        province_id: Number('31'),
        type: 'Kota',
        name: 'Tomohon',
        postal_code: '95416',
      },
      {
        id: Number('486'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Toraja Utara',
        postal_code: '91831',
      },
      {
        id: Number('487'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Trenggalek',
        postal_code: '66312',
      },
      {
        id: Number('488'),
        province_id: Number('19'),
        type: 'Kota',
        name: 'Tual',
        postal_code: '97612',
      },
      {
        id: Number('489'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Tuban',
        postal_code: '62319',
      },
      {
        id: Number('490'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Tulang Bawang',
        postal_code: '34613',
      },
      {
        id: Number('491'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Tulang Bawang Barat',
        postal_code: '34419',
      },
      {
        id: Number('492'),
        province_id: Number('11'),
        type: 'Kabupaten',
        name: 'Tulungagung',
        postal_code: '66212',
      },
      {
        id: Number('493'),
        province_id: Number('28'),
        type: 'Kabupaten',
        name: 'Wajo',
        postal_code: '90911',
      },
      {
        id: Number('494'),
        province_id: Number('30'),
        type: 'Kabupaten',
        name: 'Wakatobi',
        postal_code: '93791',
      },
      {
        id: Number('495'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Waropen',
        postal_code: '98269',
      },
      {
        id: Number('496'),
        province_id: Number('18'),
        type: 'Kabupaten',
        name: 'Way Kanan',
        postal_code: '34711',
      },
      {
        id: Number('497'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Wonogiri',
        postal_code: '57619',
      },
      {
        id: Number('498'),
        province_id: Number('10'),
        type: 'Kabupaten',
        name: 'Wonosobo',
        postal_code: '56311',
      },
      {
        id: Number('499'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Yahukimo',
        postal_code: '99041',
      },
      {
        id: Number('500'),
        province_id: Number('24'),
        type: 'Kabupaten',
        name: 'Yalimo',
        postal_code: '99481',
      },
      {
        id: Number('501'),
        province_id: Number('5'),
        type: 'Kota',
        name: 'Yogyakarta',
        postal_code: '55111',
      },
    ];

    await citiesRepository.save(cities);
  }
}
